### PR TITLE
fix: use default session timeout of 60s

### LINKED ISSUE #235: default keepalive interval
I have a camera which does not send 

> Session: timeout=x

in the SETUP response.  But it closes the connection if it does not get a keepalive.
The RFC (https://tools.ietf.org/html/rfc2326) has this to say:

> The timeout is measured in seconds, with a default of 60 seconds (1 minute).

So should a client assume a 60 second timeout if the server does not specify it?  I am looking at sessionTimeout inside rtsp.ts where it defaults to null if the timeout string is not present.  Should it default to 60 instead?  
Wireshark for instance is telling me that VLC behaves this way.

### PR DESCRIPTION
**Pull request by steabert**
The RFC https://tools.ietf.org/html/rfc2326
specifies a default session timeout of 60s.

Fixes #235

### CODE REVIEW

File: lib/utils/protocols/rtsp.ts [hunk 1]
```diff
@@ -87,19 +87,20 @@ export const sessionTimeout = (buffer: Buffer) => {
    * session-id        =  1*256( ALPHA / DIGIT / safe )
    * delta-seconds     =  1*19DIGIT
    */
+  const defaultTimeout = 60
```
Comment (lekoaf) [inline lib/utils/protocols/rtsp.ts:90]: I just want to double check, this is actually 60 seconds and not 60 milliseconds?

Don't you have some kind of constants file you can put this in? Or perhaps you prefer to keep it with it context? I'm fine with it either way.

Is this a breaking change?

Comment (steabert) [reply lib/utils/protocols/rtsp.ts:90]: This shouldn't be a breaking change, just that we will send an OPTIONS every 60s if there was no timeout specified.

**Review by barnomasoz — APPROVED** [review]
Looks good
